"""Regenerates canon/CANON.md from the verbatim directives below.
Directives are append-only and stored exactly as the user typed them (typos included).
Each carries a SHA-256 of its UTF-8 text so any alteration is detectable: run with --verify."""
import hashlib, json, pathlib, sys

HERE = pathlib.Path(__file__).parent
DIRECTIVES = [
    ("C1", "2026-09-28", "Mission",
     "I want you to build a website that does one thing, it picks stocks, it should be very advanced and all the apis or anything like that used should be free, you should aim for 7% a week and it can update investments however best you see fit if thats everyday, if thats live changing constantly or no matter what it is, you can pick as many stocks as you want but it should aim for 7% gains every week, this will only be used as a simulation it will have the account start with $1000 and you can invest that however you want and over the next month we will moniter how successfull it is, but first I want you to do deep research and create a master blueprint to make the best stock finder possible, that doesn't just follow trending stocks, but the ones that actually will grow 7% in a week"),
    ("C2", "2026-09-28", "Target is portfolio-level",
     "this means the entire portfolio should grow 7%, not neccessarily every stock choic"),
    ("C3", "2026-09-28", "Blueprint must be advanced",
     "the blueprint should be very advanced, seeing everything that creates the most accurate stradegy to the expected outcome"),
    ("C4", "2026-09-28", "Permission to set up accounts",
     "i give you permission to do all that in claude in code including making github and all that, i can get you logged into anything you need"),
    ("C5", "2026-09-28", "Continuous self-improvement",
     "it should have an advanced learning process like any ai of figuring out what isnt working and how to improve the system to fix that thing that wasnt working until we land the perfect system add this to memory files and a canon to work on"),
    ("C6", "2026-09-28", "Regular trading hours only",
     "also it should onl y trade durring daytime trading hours(continue working on what you were doing just keep that in mind"),
]

def sha(t): return hashlib.sha256(t.encode("utf-8")).hexdigest()

def build():
    lines = ["# Weekly7 Canon", "",
             "The user's directives, **verbatim** and append-only. They outrank the blueprint; the blueprint outranks the code.",
             "Generated by `canon/build_canon.py` — edit the script, never this file. Verify: `python canon/build_canon.py --verify`.", ""]
    for cid, date, title, text in DIRECTIVES:
        lines += [f"## {cid} — {title} ({date})", "", "> " + text, "", f"`sha256: {sha(text)}`", ""]
    (HERE / "CANON.md").write_text("\n".join(lines), encoding="utf-8", newline="\n")
    (HERE / "canon.lock.json").write_text(json.dumps({c: sha(t) for c, _, _, t in DIRECTIVES}, indent=2), encoding="utf-8", newline="\n")

def verify():
    lock = json.loads((HERE / "canon.lock.json").read_text(encoding="utf-8"))
    bad = [c for c, _, _, t in DIRECTIVES if lock.get(c) != sha(t)]
    missing = [c for c in lock if c not in {d[0] for d in DIRECTIVES}]
    if bad or missing:
        print("CANON ALTERED:", bad, "MISSING:", missing); sys.exit(1)
    print(f"canon ok: {len(lock)} directives")

if __name__ == "__main__":
    verify() if "--verify" in sys.argv else build()
