"""Bible 39.0.30 ("documentation reflects actual state") made mechanical: docs/ARCHITECTURE.md is GENERATED from the
code - every engine module's docstring summary, its public functions and classes with signatures, its size, and the
test files that import it. `--check` fails (exit 1) when the committed file differs from a fresh generation, so CI
catches documentation that has drifted from the code.

usage: python scripts/arch_doc.py [--check]"""
import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "ARCHITECTURE.md"
NL = chr(10)


def summary(doc):
    if not doc:
        return "(no module docstring)"
    first = doc.strip().split(NL + NL)[0]
    return " ".join(first.split())


def signature(fn):
    a = fn.args
    names = [x.arg for x in a.posonlyargs + a.args]
    if a.vararg:
        names.append("*" + a.vararg.arg)
    names += [x.arg for x in a.kwonlyargs]
    if a.kwarg:
        names.append("**" + a.kwarg.arg)
    return f"{fn.name}({', '.join(names)})"


def public_api(tree):
    out = []
    for n in tree.body:
        if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and not n.name.startswith("_"):
            out.append(("def", signature(n), summary(ast.get_docstring(n))))
        elif isinstance(n, ast.ClassDef) and not n.name.startswith("_"):
            methods = [signature(m) for m in n.body
                       if isinstance(m, (ast.FunctionDef, ast.AsyncFunctionDef)) and not m.name.startswith("_")]
            out.append(("class", n.name + (f" [{', '.join(methods[:8])}{', ...' if len(methods) > 8 else ''}]" if methods else ""),
                        summary(ast.get_docstring(n))))
    return out


def test_importers():
    """{module name: [test files that import engine.<module>]}"""
    imp = {}
    for t in sorted((ROOT / "tests").rglob("test_*.py")):
        try:
            tree = ast.parse(t.read_text(encoding="utf-8", errors="replace"))
        except SyntaxError:
            continue
        mods = set()
        for n in ast.walk(tree):
            if isinstance(n, ast.ImportFrom) and n.module:
                if n.module == "engine":
                    mods.update(a.name for a in n.names)
                elif n.module.startswith("engine."):
                    mods.add(n.module.split(".")[1])
            elif isinstance(n, ast.Import):
                mods.update(a.name.split(".")[1] for a in n.names if a.name.startswith("engine."))
        for m in mods:
            imp.setdefault(m, []).append(t.relative_to(ROOT).as_posix())
    return imp


def generate():
    imp = test_importers()
    mods = sorted((ROOT / "engine").glob("*.py"))
    L = ["# Weekly7 architecture (GENERATED - do not edit)", "",
         "Generated by `scripts/arch_doc.py` from the code itself; CI fails if this file drifts from the code.",
         "Governing documents: `canon/CANON.md` (owner directives, verbatim) > `BIBLE.md` > `MASTER_BLUEPRINT.md` > code.", "",
         f"{len(mods)} engine modules, {sum(len(m.read_text(encoding='utf-8', errors='replace').splitlines()) for m in mods):,} lines.", "",
         "| module | lines | tests importing it | purpose |", "|---|---:|---:|---|"]
    detail = []
    for m in mods:
        if m.name == "__init__.py":
            continue
        src = m.read_text(encoding="utf-8", errors="replace")
        try:
            tree = ast.parse(src)
        except SyntaxError as e:
            L.append(f"| {m.stem} | {len(src.splitlines())} | - | SYNTAX ERROR: {e} |"); continue
        s = summary(ast.get_docstring(tree))
        tests = imp.get(m.stem, [])
        L.append(f"| `{m.stem}` | {len(src.splitlines())} | {len(tests)} | {s[:180].replace('|', '/')} |")
        detail += ["", f"## engine.{m.stem}", "", s, ""]
        api = public_api(tree)
        if api:
            detail += [f"- `{kind} {sig}`" + (f" - {doc[:160]}" if doc and doc != "(no module docstring)" else "") for kind, sig, doc in api]
        detail += ["", "Tests: " + (", ".join(f"`{t}`" for t in tests) if tests else "_none import it directly_")]
    return NL.join(L + detail) + NL


def main():
    text = generate()
    if "--check" in sys.argv:
        cur = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if cur != text:
            print("docs/ARCHITECTURE.md is out of date with the code - run: python scripts/arch_doc.py")
            sys.exit(1)
        print("docs/ARCHITECTURE.md matches the code")
        return
    OUT.write_text(text, encoding="utf-8", newline=NL)
    print(f"wrote {OUT} ({len(text):,} chars)")


if __name__ == "__main__":
    main()
