"""Write state/build/CHECKLIST_REMAINING.md: every C77 checklist item that is not yet TESTING (or better), with exactly what is
missing - code, test, evidence or validation. Computed from state/build/CREATOR_MASTER_CHECKLIST.json (which
scripts/creator_checklist_status.py computes from evidence) and state/validation/VALIDATION_REPORT.md. Run the status script first."""
from __future__ import annotations

import json
import re
from collections import Counter
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CHECK = ROOT / "state" / "build" / "CREATOR_MASTER_CHECKLIST.json"
VALID = ROOT / "state" / "validation" / "VALIDATION_REPORT.md"
OUT = ROOT / "state" / "build" / "CHECKLIST_REMAINING.md"
DONE = ("TESTING", "VALIDATED")

# exactly what is missing, per substantive item (everything else gets the generic text for its status)
MISSING: dict[str, str] = {
    "CR098": "CODE + TEST + EVIDENCE: no component runs integration tests (tests that exercise two or more components together "
             "as a product of the Creator); testgen.py generates per-module unit/characterisation tests only.",
    "CR151": "CODE + TEST + EVIDENCE: no audit check covers the recursion loop (e.g. a recursion step adopted without a real "
             "IMPROVEMENT claim, or one that touched the holdout); creator/audit/checks.py has no recursion check or adversary attack.",
    "CR142": "EVIDENCE: creator/recursion.py + scripts/creator_recurse.py are tested on a stand-in workload, but no real "
             "RECURSION_STEP finding exists in state/creator/ledger.jsonl. Run scripts/creator_recurse.py --steps 2 (dev split only).",
    "CR143": "EVIDENCE: same as CR142 - the recursive loop has never run on the real workload and been adopted by evidence.",
    "CR197": "EVIDENCE: needs one adopted real recursion step whose measured development-process improvement (IMPROVEMENT verdict "
             "on the dev workload, guard intact) is in the ledger; none exists.",
    "CR198": "EVIDENCE: needs a second real recursion step under different conditions (new seed / different weakness) that again "
             "adopts by evidence; none exists.",
    "CR204": "TEST + EVIDENCE: audit checks find hidden failures they know of (stale_done, fake_adoption); nothing enumerates "
             "FAILED/REJECTED/regressed ledger records and proves each is resolved or disclosed. Needs a check plus an adversary "
             "attack that hides a failure, then a clean run.",
    "CR208": "TEST + EVIDENCE: claims are recomputed (check_claim_recompute) and the real ledger reproduces 10/10, but there is no "
             "register of the MAJOR claims with evidence for each; needs the claim register plus a check that each is backed.",
}


def generic(it: dict[str, Any]) -> str:
    st, n = it["status"], it["notes"]
    if it["description"].startswith("SECTION REQUIREMENT"):
        if st == "NOT_STARTED" and "no measurable member" in n:
            return "DEFINITION: this section is doctrine/role/process; it has no measurable member item. Needs member items " \
                   "(or owner ruling) before a status can be computed."
        return f"MEMBERS: {n.split(';')[0]}; and the section's own bullets still need individual verification, then the validator."
    if st == "IMPLEMENTED" and it["id"] <= "CR036":
        return "TEST + VALIDATION: reconnaissance record only (state/build/CREATOR_PHASE0_LEDGER.json); no test asserts it and no validator has checked it."
    if st == "IMPLEMENTED":
        return "TEST/EVIDENCE: " + n
    if st == "NOT_STARTED":
        return "CODE + TEST + EVIDENCE: no mapped component."
    return n


def validation_rows() -> list[str]:
    if not VALID.is_file():
        return []
    return [ln for ln in VALID.read_text(encoding="utf-8").splitlines() if re.match(r"\| (K\d+|NEW-)", ln)]


def main() -> int:
    data = json.loads(CHECK.read_text(encoding="utf-8"))
    items = data["items"]
    cnt = Counter(i["status"] for i in items)
    rem = [i for i in items if i["status"] not in DONE]
    lines = ["# C77 checklist - the true remaining work", "",
             "Generated by scripts/checklist_remaining.py from state/build/CREATOR_MASTER_CHECKLIST.json. Nothing here is VALIDATED "
             "by hand; every status is computed by scripts/creator_checklist_status.py from test and audit evidence.", "",
             f"Counts: {dict(cnt)} ({len(items)} items). Not yet TESTING or better: {len(rem)}.", "",
             "TESTING items are not done either: VALIDATED needs the independent validator "
             "(state/validation/VALIDATION_REPORT.md). Validator verdicts per component:", ""]
    lines += ["```"] + validation_rows() + ["```", ""]
    members = [i for i in rem if not i["description"].startswith("SECTION REQUIREMENT")]
    sections = [i for i in rem if i["description"].startswith("SECTION REQUIREMENT")]
    p0 = [i for i in members if i["status"] == "IMPLEMENTED" and i["id"] <= "CR036"]
    rest = [i for i in members if i not in p0]
    lines += [f"## A. Substantive items ({len(rest)})", ""]
    for i in sorted(rest, key=lambda x: x["id"]):
        lines.append(f"- {i['id']} [{i['status']}] {i['group'].split(' / ')[-1]}: {i['description']}  \n  MISSING: "
                     f"{MISSING.get(i['id'], generic(i))}")
    lines += ["", f"## B. Phase-0 reconnaissance records ({len(p0)}), IMPLEMENTED", "",
              f"{p0[0]['id']}..{p0[-1]['id']} " if p0 else "none", "",
              "MISSING for every one: a test that asserts the record and independent validation. The record itself "
              "(state/build/CREATOR_PHASE0_LEDGER.json, scripts/phase0_recon.py) exists.", ""]
    lines += [f"## C. SECTION REQUIREMENT roll-ups ({len(sections)})", "",
              "Computed from the weakest member of the section's mapped groups (capped at IMPLEMENTED). They move only when "
              "their members move.", ""]
    by: dict[str, list[dict[str, Any]]] = {}
    for i in sections:
        by.setdefault(generic(i).split(":")[0], []).append(i)
    for kind, group in by.items():
        lines += [f"### {kind} ({len(group)})", ""]
        for i in group:
            lines.append(f"- {i['id']} [{i['status']}] {i['group'].replace('SECTION / ', '')}: {i['notes'].split(';')[0]}")
        lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(OUT, len(rem), "remaining")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
