"""Train creator.chooser from lessons + measured outcomes; deterministic; writes state/creator/chooser.json.

Sources: (a) adopted lessons mapped onto the action space and (b) measured outcomes of student attempts (adopted = positive, measured
rejection = negative, cancelled/error = no signal) from the lesson logs given with --lessons (repeatable); (c) the teacher's synthetic
contrastive lessons (state/creator/lessons_contrast.jsonl, plus `--contrast-scale N` regenerated by make_contrast_lessons.make).
Before training, the rows are proven disjoint from the held-out bench seeds (no identical source text, no identical objective)."""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
for p in (ROOT, ROOT / "scripts"):
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))

from creator import chooser as C  # noqa: E402
from creator.curriculum import LessonLog  # noqa: E402

FORBIDDEN_SEEDS = {201, 202, 203, 301, 302, 303}


def assert_disjoint(rows: list[C.Row], seeds: list[int]) -> dict[str, int]:
    """The held-out bench tasks (any hardness) must share no source text and no objective with a training row."""
    import action_choice_bench as B
    tasks = [t for sd in seeds for hard in (False, True) for t in B.generate_tasks(30, sd, hard)]
    srcs, objs = {t.src for t in tasks}, {t.objective.strip().lower() for t in tasks}
    bad_src = sum(r.src in srcs for r in rows)
    bad_obj = sum(r.objective.strip().lower() in objs for r in rows)
    assert not set(seeds) & FORBIDDEN_SEEDS, "held-out seeds overlap earlier dev/test seeds"
    assert bad_src == 0 and bad_obj == 0, f"training rows overlap held-out tasks: sources={bad_src} objectives={bad_obj}"
    return {"heldout_tasks": len(tasks), "overlap_sources": bad_src, "overlap_objectives": bad_obj}


def build_rows(lesson_paths: list[Path], contrast_scale: int = 1) -> tuple[list[C.Row], dict[str, Any]]:
    import make_contrast_lessons as M
    rows: list[C.Row] = []
    info: dict[str, Any] = {}
    for p in lesson_paths:
        got = C.lesson_rows(LessonLog(p).lessons())
        info[Path(p).name] = len(got)
        rows += got
    if contrast_scale > 0:
        got = C.lesson_rows(M.make(contrast_scale))
        info[f"contrast_x{contrast_scale}"] = len(got)
        rows += got
    seen: set[tuple[str, str, tuple[int, ...], int]] = set()
    uniq = []
    for r in rows:
        k = (r.src, r.objective, tuple(r.chosen), r.sign)
        if k not in seen:
            seen.add(k)
            uniq.append(r)
    info["total_rows"], info["deduped"] = len(rows), len(uniq)
    return uniq, info


def retrain_with_practice(state: Path, epochs: int = 200, contrast_scale: int = 4, force: bool = False,
                          holdout_folds: int = 5) -> dict[str, Any] | None:
    """Retrain on lessons + practice rows, deterministic, and persist state/chooser.json. Returns None (and does nothing) when no new
    practice row or lesson has arrived since the last logged retrain. Appends one record to state/practice_log.jsonl:
    before = a chooser trained on the lessons only, scored on every practice decision; after = practice_holdout (held out by file) of
    lessons + practice rows. Practice rows never enter the shadow rule (it reads lessons.jsonl only)."""
    state = Path(state)
    log = state / "practice_log.jsonl"
    p_rows = C.practice_rows(state / "practice_rows.jsonl", state / "practice_src")
    paths = [state / "lessons.jsonl", state / "lessons_contrast.jsonl"]
    l_rows, info = build_rows([p for p in paths if p.exists()], contrast_scale)
    sig = f"p{len(p_rows)}:l{len(l_rows)}"
    last = ""
    try:
        for ln in log.read_text(encoding="utf-8").splitlines():
            try:
                last = json.loads(ln).get("signature", last)
            except ValueError:
                continue
    except OSError:
        pass
    if sig == last and not force:
        return None
    if not p_rows:
        return None
    t0, c0 = time.monotonic(), time.process_time()
    assert_disjoint(l_rows + p_rows, [401, 402, 403])
    base = C.Chooser().fit(l_rows, epochs=epochs) if l_rows else C.Chooser()
    pos = [r for r in p_rows if r.sign > 0 and len(r.chosen) < len(r.cands)]
    before_hit = sum(1 for r in pos if base.trained and (base.pick(r.objective, r.cands, {c.path: r.src for c in r.cands}) or 0) - 1 in r.chosen)
    before = {"decisions": len(pos), "chooser_top1": before_hit / len(pos) if pos else None}
    after = C.practice_holdout(l_rows + p_rows, folds=holdout_folds, epochs=epochs)
    ch = C.Chooser().fit(l_rows + p_rows, epochs=epochs)
    ch.meta["sources"] = {**info, "practice_rows": len(p_rows)}
    ch.save(state / "chooser.json")
    rec = {"at": time.strftime("%Y-%m-%dT%H:%M:%S"), "signature": sig, "practice_rows": len(p_rows), "lesson_rows": len(l_rows),
           "before": before, "after": after, "seconds": round(time.monotonic() - t0, 1)}
    with log.open("a", encoding="utf-8", newline="\n") as f:
        f.write(json.dumps(rec, sort_keys=True) + "\n")
    from creator import slowpath as SP                  # the slow-path detector sees every retrain (it was the 44-minute thought)
    SP.record(state, "chooser.retrain", time.monotonic() - t0, time.process_time() - c0, rows=len(l_rows) + len(p_rows))
    return rec


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--lessons", action="append", default=None, help="lesson JSONL (repeatable)")
    ap.add_argument("--contrast-scale", type=int, default=4)
    ap.add_argument("--heldout-seeds", default="401,402,403")
    ap.add_argument("--epochs", type=int, default=300)
    ap.add_argument("--practice", action="store_true", help="retrain on lessons + practice rows (state/creator), log before/after")
    ap.add_argument("--out", default=str(C.DEFAULT_PATH))
    a = ap.parse_args()
    if a.practice:
        print(json.dumps(retrain_with_practice(ROOT / "state" / "creator", a.epochs, a.contrast_scale), indent=1))
        return 0
    paths = [Path(x) for x in (a.lessons or [str(ROOT / "state/creator/lessons.jsonl"), str(ROOT / "state/creator/lessons_contrast.jsonl")])]
    rows, info = build_rows([p for p in paths if p.exists()], a.contrast_scale)
    info["disjoint"] = assert_disjoint(rows, [int(x) for x in a.heldout_seeds.split(",")])
    ch = C.Chooser().fit(rows, epochs=a.epochs)
    ch.meta["sources"] = info
    ch.save(Path(a.out))
    pos = [r for r in rows if r.sign > 0]
    acc = sum((ch.pick(r.objective, r.cands, {r.cands[0].path: r.src}) or 0) - 1 in r.chosen for r in pos) / max(1, len(pos))
    print(json.dumps({"sources": info, "train_top1": round(acc, 3), "out": a.out}, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
