"""Train creator.chooser from lessons + measured outcomes; deterministic; writes state/creator/chooser.json.

Sources: (a) adopted lessons mapped onto the action space and (b) measured outcomes of student attempts (adopted = positive, measured
rejection = negative, cancelled/error = no signal) from the lesson logs given with --lessons (repeatable); (c) the teacher's synthetic
contrastive lessons (state/creator/lessons_contrast.jsonl, plus `--contrast-scale N` regenerated by make_contrast_lessons.make).
Before training, the rows are proven disjoint from the held-out bench seeds (no identical source text, no identical objective)."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
for p in (ROOT, ROOT / "scripts"):
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))

from creator import chooser as C  # noqa: E402
from creator.curriculum import LessonLog  # noqa: E402

FORBIDDEN_SEEDS = {201, 202, 203, 301, 302, 303}


def assert_disjoint(rows: list[C.Row], seeds: list[int]) -> dict[str, int]:
    """The held-out bench tasks (any hardness) must share no source text and no objective with a training row."""
    import action_choice_bench as B
    tasks = [t for sd in seeds for hard in (False, True) for t in B.generate_tasks(30, sd, hard)]
    srcs, objs = {t.src for t in tasks}, {t.objective.strip().lower() for t in tasks}
    bad_src = sum(r.src in srcs for r in rows)
    bad_obj = sum(r.objective.strip().lower() in objs for r in rows)
    assert not set(seeds) & FORBIDDEN_SEEDS, "held-out seeds overlap earlier dev/test seeds"
    assert bad_src == 0 and bad_obj == 0, f"training rows overlap held-out tasks: sources={bad_src} objectives={bad_obj}"
    return {"heldout_tasks": len(tasks), "overlap_sources": bad_src, "overlap_objectives": bad_obj}


def build_rows(lesson_paths: list[Path], contrast_scale: int = 1) -> tuple[list[C.Row], dict[str, Any]]:
    import make_contrast_lessons as M
    rows: list[C.Row] = []
    info: dict[str, Any] = {}
    for p in lesson_paths:
        got = C.lesson_rows(LessonLog(p).lessons())
        info[Path(p).name] = len(got)
        rows += got
    if contrast_scale > 0:
        got = C.lesson_rows(M.make(contrast_scale))
        info[f"contrast_x{contrast_scale}"] = len(got)
        rows += got
    seen: set[tuple[str, str, tuple[int, ...], int]] = set()
    uniq = []
    for r in rows:
        k = (r.src, r.objective, tuple(r.chosen), r.sign)
        if k not in seen:
            seen.add(k)
            uniq.append(r)
    info["total_rows"], info["deduped"] = len(rows), len(uniq)
    return uniq, info


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--lessons", action="append", default=None, help="lesson JSONL (repeatable)")
    ap.add_argument("--contrast-scale", type=int, default=4)
    ap.add_argument("--heldout-seeds", default="401,402,403")
    ap.add_argument("--epochs", type=int, default=300)
    ap.add_argument("--out", default=str(C.DEFAULT_PATH))
    a = ap.parse_args()
    paths = [Path(x) for x in (a.lessons or [str(ROOT / "state/creator/lessons.jsonl"), str(ROOT / "state/creator/lessons_contrast.jsonl")])]
    rows, info = build_rows([p for p in paths if p.exists()], a.contrast_scale)
    info["disjoint"] = assert_disjoint(rows, [int(x) for x in a.heldout_seeds.split(",")])
    ch = C.Chooser().fit(rows, epochs=a.epochs)
    ch.meta["sources"] = info
    ch.save(Path(a.out))
    pos = [r for r in rows if r.sign > 0]
    acc = sum((ch.pick(r.objective, r.cands, {r.cands[0].path: r.src}) or 0) - 1 in r.chosen for r in pos) / max(1, len(pos))
    print(json.dumps({"sources": info, "train_top1": round(acc, 3), "out": a.out}, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
